[tools]
elixir = "1.18"
node = "22"
zig = "0.14.0"

# high level tasks

[tasks.prerelease]
depends = ["build"]
depends_post = ["test"]

[tasks.build]
run = ["mix setup", "mix compile --no-optional-deps --warnings-as-errors", "npm i", "npm run build"]

[tasks.test]
run = ["mix test", "mix format --check-formatted", "mix deps --check-unused", "mix deps.unlock --all", "mix deps.get", "mix test", "git checkout mix.lock"]

# low level tasks

[tasks.mcp_inspect]
run = "MCP_INSPECTOR=true npx @modelcontextprotocol/inspector node dist/index.js"

[tasks.build_docker_smithery]
run = "docker build -t smithery . -f Dockerfile"

[tasks.start_mcp_server]
run = "PORT=8080 node dist/index.js"
