name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - run: sudo apt-get -y install xz-utils

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.18'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build release with Burrito
        run: |
          mix deps.compile
          MIX_ENV=prod mix release

      - name: Generate checksums
        run: |
          cd burrito_out
          node -e '
            const crypto = require("crypto");
            const fs = require("fs");
            const files = ["hexdocs_mcp_windows.exe", "hexdocs_mcp_linux", "hexdocs_mcp_macos", "hexdocs_mcp_macos_arm"];
            const checksums = files.map(file => {
              try {
                const hash = crypto.createHash("sha256");
                const data = fs.readFileSync(file);
                hash.update(data);
                return `${hash.digest("hex")}  ${file}`;
              } catch (error) {
                console.error(`Error processing ${file}:`, error);
                process.exit(1);
              }
            });
            fs.writeFileSync("SHA256SUMS", checksums.join("\n") + "\n");
          '
          cd ..

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Export public key and sign checksums
        run: |
          cd burrito_out
          # Export the public key
          gpg --armor --export ${{ secrets.GPG_KEY_ID }} > SIGNING_KEY.asc
          # Sign the checksums
          gpg --detach-sign --armor SHA256SUMS
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            burrito_out/hexdocs_mcp_windows.exe
            burrito_out/hexdocs_mcp_linux
            burrito_out/hexdocs_mcp_macos
            burrito_out/hexdocs_mcp_macos_arm
            burrito_out/SHA256SUMS
            burrito_out/SHA256SUMS.asc
            burrito_out/SIGNING_KEY.asc
        if: startsWith(github.ref, 'refs/tags/')
      